### ISSUE TITLE
Add WebTrilinos repository to GitHub

### ISSUE THREAD

**Issue by jwillenbring** [trilinos/WebTrilinos#1]
@trilinos/framework 

Next action: Brent - please either point me to where the WebTrilinos repo lives, or upload it to the new "WebTrilinos" repo that is currently empty on GitHub

Definition of Done: WebTrilinos source code has been added to the WebTrilinos repo in the Trilinos organization on GitHub.

Background

Mike Heroux is doing a tutorial in a few weeks and his hosts need to install WebTrilinos locally for him to use. They do not support Docker, so we need to get the WebTrilinos repository that was split off of Trilinos onto GitHub. It will be non-trivial to install, and I want to give them as much time as possible to get things working. I looked at the directory structure of the current Docker images, and given how WebTrilinos is installed, it may not make sense to put it in the same repo as the Trilinos_tutorial, at least for now. This is because WebTrilinos actually gets installed in /var/www/html, or wherever you are pointing your Apache server to, while Trilinos_tutorial just goes in the home directory. Further "installing" WebTrilinos is currently just copying the relevant files. Eventually, I would like to sync up the example for WebTrilinos and Trilinos_tutorial. If or when that happens, we could look at putting both in the same repo, or more likely, since Trilinos seems to be on a path to supporting multiple repos for other reasons, we could probably just extend that support to this. The only concern I have about the latter is the potential to need to duplicate example files in two places if we have a docker image that contains both WebTrilinos and Trilinos_tutorial, which I think makes sense.

**Comment by bmpersc** [comment]
I have pushed the WebTrilinos repository that was broken out of Trilinos when we first moved to Trilinos. Only the master branch was pushed, but we still have others if needed. Please report if there are issues with what has been pushed.

**Comment by jwillenbring** [comment]
Thanks @bmpersc
